# Generated by Django 4.2.7 on 2024-09-19 21:35

import Mashinani.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_no', models.DecimalField(decimal_places=0, help_text='Enter Account Number', max_digits=50, primary_key=True, serialize=False)),
                ('account_name', models.CharField(help_text='Enter Account Name', max_length=100)),
                ('account_bal', models.DecimalField(decimal_places=2, help_text='Enter Account Balance', max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('allocation_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('allocation_no', models.CharField(blank=True, help_text='Enter the Allocation Number', max_length=50, unique=True)),
                ('lender_no', models.CharField(help_text='Enter Lender Number:', max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Enter Amount to Allocate', max_digits=15)),
                ('interest_rate', models.DecimalField(decimal_places=2, help_text='Enter Interest Rate', max_digits=15)),
                ('allocation_date', models.DateField(blank=True, help_text='Enter Date of Allocation')),
            ],
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('bank_no', models.CharField(help_text='Enter Bank Number', max_length=50, primary_key=True, serialize=False, unique=True)),
                ('bank_name', models.CharField(help_text='Enter Bank Name', max_length=50, unique=True)),
                ('email_address', models.EmailField(help_text='Enter Email Address', max_length=50, unique=True)),
                ('phone_number', models.CharField(help_text='Enter phone number in the format 0798073204 or +254798073404', max_length=13, validators=[Mashinani.validators.validate_kenyan_phone_number])),
                ('username', models.CharField(blank=True, help_text='Enter Username', max_length=50)),
                ('account_no', models.ForeignKey(help_text='Choose Account Number', on_delete=django.db.models.deletion.CASCADE, to='Mashinani.account')),
            ],
        ),
        migrations.CreateModel(
            name='Constituency',
            fields=[
                ('constituency_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('constituency_name', models.CharField(help_text='Enter Constituency Name', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='County',
            fields=[
                ('county_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('county_name', models.CharField(help_text='Enter County Name', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Disbursement',
            fields=[
                ('disbursement_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('transaction_no', models.CharField(blank=True, help_text='Enter the Transaction Number', max_length=30, unique=True)),
                ('application_no', models.CharField(help_text='Enter the Application Number', max_length=50)),
                ('disbursed_amount', models.DecimalField(decimal_places=2, help_text='Enter Amount to Disburse', max_digits=15)),
                ('disbursement_date', models.DateField(help_text='Enter Date of Disbursement')),
                ('loan_duration_months', models.IntegerField(help_text='Loan Duration in Months')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_no', models.CharField(help_text='Enter Group Number', max_length=50, primary_key=True, serialize=False, unique=True)),
                ('group_name', models.CharField(help_text='Enter Group Name', max_length=100)),
                ('email_address', models.EmailField(help_text='Enter Email Address', max_length=50, unique=True)),
                ('phone_number', models.CharField(help_text='Enter phone number in the format 0798073204 or +254798073404', max_length=13, validators=[Mashinani.validators.validate_kenyan_phone_number])),
                ('username', models.CharField(blank=True, help_text='Enter Username', max_length=50)),
                ('account_no', models.ForeignKey(help_text='Account Number', on_delete=django.db.models.deletion.CASCADE, to='Mashinani.account')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('message_no', models.CharField(help_text='Enter Message Number', max_length=50)),
                ('sender_username', models.CharField(help_text='Enter Sender Username', max_length=50)),
                ('recipient_username', models.CharField(help_text='Enter Recipient Username', max_length=50)),
                ('message_name', models.CharField(help_text='Enter Message Name', max_length=50)),
                ('message_description', models.CharField(help_text='Enter Message Description', max_length=50)),
                ('message_date', models.DateField(help_text='Enter Date Sent')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('role_name', models.CharField(help_text='Enter Role Name', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('ward_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('ward_name', models.CharField(help_text='Enter Ward Name', max_length=100)),
                ('constituency_id', models.ForeignKey(help_text='Choose the Constituency Name', on_delete=django.db.models.deletion.CASCADE, to='Mashinani.constituency')),
            ],
        ),
        migrations.CreateModel(
            name='System_User',
            fields=[
                ('username', models.EmailField(help_text='Enter a valid Username', max_length=50, primary_key=True, serialize=False, unique=True)),
                ('password_hash', models.CharField(help_text='Enter a valid password', max_length=128)),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mashinani.role')),
            ],
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mashinani.system_user')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('member_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('national_id_no', models.DecimalField(decimal_places=0, help_text='Enter National Identification Number:', max_digits=20, unique=True, validators=[Mashinani.validators.validate_kenyan_id])),
                ('email_address', models.EmailField(help_text='Enter Email Address', max_length=50, unique=True)),
                ('username', models.EmailField(help_text='Enter Email Address', max_length=50, unique=True)),
                ('first_name', models.CharField(help_text='Enter First Name', max_length=50)),
                ('last_name', models.CharField(help_text='Enter Last Name', max_length=50)),
                ('phone_number', models.CharField(help_text='Enter phone number in the format 0798073204 or +254798073404', max_length=13, validators=[Mashinani.validators.validate_kenyan_phone_number])),
                ('dob', models.DateField(help_text='Enter Date of Birth')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], help_text='Enter Member Gender', max_length=10)),
                ('grp_worth', models.DecimalField(decimal_places=2, default=0.0, help_text='Enter Group Worth in Kshs.', max_digits=20)),
                ('account_no', models.CharField(default='00000000', help_text='Account Number', max_length=50)),
                ('approved', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', help_text='Is the member approved', max_length=3)),
                ('loan_status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', help_text='Member Loan Status', max_length=6)),
                ('group_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mashinani.group')),
            ],
        ),
        migrations.CreateModel(
            name='Loanee',
            fields=[
                ('loanee_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('approved', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='yes', help_text='Is member approved', max_length=3)),
                ('applied', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', help_text='Does member has an hanging application', max_length=3)),
                ('national_id_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mashinani.member')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('loan_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('payment_no', models.CharField(blank=True, help_text='Enter the Payment Number', max_length=30)),
                ('principal', models.DecimalField(decimal_places=2, help_text='Enter Amount to Pay', max_digits=15)),
                ('loan_interest', models.DecimalField(decimal_places=2, help_text='Interest Rate', max_digits=15)),
                ('principal_interest', models.DecimalField(decimal_places=2, help_text='Total Amount', max_digits=15)),
                ('amount_paid', models.DecimalField(decimal_places=2, help_text='Total Paid', max_digits=15)),
                ('balance', models.DecimalField(decimal_places=2, help_text='Balance', max_digits=15)),
                ('loan_date', models.DateField(default='2024-01-01', help_text='Enter Date of last Payment')),
                ('bank_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mashinani.bank')),
                ('national_id_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mashinani.member')),
                ('transaction_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mashinani.disbursement')),
            ],
        ),
        migrations.CreateModel(
            name='Guarantor',
            fields=[
                ('guarantor_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('national_id', models.DecimalField(decimal_places=0, help_text='Enter National Identification Number:', max_digits=8, unique=True, validators=[Mashinani.validators.validate_kenyan_id])),
                ('email_address', models.EmailField(help_text='Enter Email Address', max_length=50, unique=True)),
                ('first_name', models.CharField(help_text='Enter First Name', max_length=30)),
                ('last_name', models.CharField(help_text='Enter Last Name', max_length=30)),
                ('username', models.CharField(blank=True, help_text='Enter Username', max_length=50)),
                ('phone_number', models.CharField(help_text='Enter phone number in the format 0798073204 or +254798073404', max_length=13, validators=[Mashinani.validators.validate_kenyan_phone_number])),
                ('dob', models.DateField(help_text='Enter Date of Birth')),
                ('occupation', models.CharField(help_text='Enter Occupation', max_length=100)),
                ('account_no', models.ForeignKey(help_text='Choose Account Number', on_delete=django.db.models.deletion.CASCADE, to='Mashinani.account')),
                ('ward', models.ForeignKey(help_text='Choose the Ward', on_delete=django.db.models.deletion.CASCADE, to='Mashinani.ward')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='guarantor',
            field=models.ForeignKey(help_text='Choose the Guarantor', on_delete=django.db.models.deletion.CASCADE, to='Mashinani.guarantor'),
        ),
        migrations.AddField(
            model_name='group',
            name='ward',
            field=models.ForeignKey(help_text='Choose Ward of Operation', on_delete=django.db.models.deletion.CASCADE, to='Mashinani.ward'),
        ),
        migrations.AddField(
            model_name='disbursement',
            name='national_id_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mashinani.member'),
        ),
        migrations.CreateModel(
            name='Defaulter',
            fields=[
                ('national_id_no', models.DecimalField(decimal_places=0, help_text='Enter National Identification Number:', max_digits=8, primary_key=True, serialize=False, unique=True, validators=[Mashinani.validators.validate_kenyan_id])),
                ('amount_owed', models.DecimalField(decimal_places=2, help_text='Enter Amount Owed', max_digits=15)),
                ('submission_date', models.DateField(blank=True, help_text='Enter Date of Submission')),
                ('bank_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mashinani.bank')),
            ],
        ),
        migrations.AddField(
            model_name='constituency',
            name='county_id',
            field=models.ForeignKey(help_text='Choose the County Name', on_delete=django.db.models.deletion.CASCADE, to='Mashinani.county'),
        ),
        migrations.AddField(
            model_name='bank',
            name='constituency',
            field=models.ForeignKey(help_text='Choose the Constituency', on_delete=django.db.models.deletion.CASCADE, to='Mashinani.constituency'),
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('application_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('application_no', models.CharField(blank=True, help_text='Enter the Application Number', max_length=50, unique=True)),
                ('allocation_no', models.CharField(help_text='Enter the Allocation Number', max_length=50)),
                ('loan_amount', models.DecimalField(decimal_places=2, help_text='Enter Amount to Request', max_digits=15)),
                ('proposed_amount', models.DecimalField(decimal_places=2, help_text='Enter Amount Proposed', max_digits=15)),
                ('application_date', models.DateField(blank=True, help_text='Enter Date of Application')),
                ('national_id_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mashinani.member')),
            ],
        ),
    ]
