# Generated by Django 4.2.7 on 2024-09-19 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mashinani', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='loan_bal',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Loan Balance', max_digits=20),
        ),
    ]
