# Generated by Django 4.2.7 on 2024-09-19 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mashinani', '0002_member_loan_bal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allocation',
            old_name='lender_no',
            new_name='bank_no',
        ),
        migrations.RenameField(
            model_name='guarantor',
            old_name='national_id',
            new_name='national_id_no',
        ),
        migrations.AlterField(
            model_name='application',
            name='allocation_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mashinani.allocation'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='account_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mashinani.account'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='constituency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mashinani.constituency'),
        ),
        migrations.AlterField(
            model_name='constituency',
            name='county_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mashinani.county'),
        ),
        migrations.AlterField(
            model_name='disbursement',
            name='application_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mashinani.application'),
        ),
        migrations.AlterField(
            model_name='group',
            name='account_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mashinani.account'),
        ),
        migrations.AlterField(
            model_name='group',
            name='guarantor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mashinani.guarantor'),
        ),
        migrations.AlterField(
            model_name='group',
            name='ward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mashinani.ward'),
        ),
        migrations.AlterField(
            model_name='guarantor',
            name='account_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mashinani.account'),
        ),
        migrations.AlterField(
            model_name='guarantor',
            name='ward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mashinani.ward'),
        ),
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], help_text='Enter Member Gender', max_length=10),
        ),
        migrations.AlterField(
            model_name='ward',
            name='constituency_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mashinani.constituency'),
        ),
    ]
