# Generated by Django 4.2.7 on 2024-09-21 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mashinani', '0005_rename_account_no_group_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='system_user',
            name='role_id',
        ),
        migrations.AddField(
            model_name='system_user',
            name='role_name',
            field=models.CharField(default='Null', help_text='Enter a valid role', max_length=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='allocation',
            name='bank_no',
            field=models.CharField(help_text='Enter Bank Number:', max_length=100),
        ),
    ]
