# Generated by Django 4.2.7 on 2024-09-26 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mashinani', '0006_remove_system_user_role_id_system_user_role_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='allocation_no',
            field=models.CharField(blank=True, help_text='Enter the Allocation Number', max_length=50),
        ),
        migrations.AlterField(
            model_name='application',
            name='national_id_no',
            field=models.CharField(help_text='Enter National Identification Number:', max_length=100),
        ),
        migrations.AlterField(
            model_name='disbursement',
            name='application_no',
            field=models.CharField(blank=True, help_text='Enter the Application Number', max_length=50),
        ),
        migrations.AlterField(
            model_name='disbursement',
            name='national_id_no',
            field=models.CharField(help_text='Enter National Identification Number:', max_length=100),
        ),
        migrations.AlterField(
            model_name='loan',
            name='bank_no',
            field=models.CharField(help_text='Enter Bank Number:', max_length=100),
        ),
        migrations.AlterField(
            model_name='loan',
            name='national_id_no',
            field=models.CharField(help_text='Enter National Identification Number:', max_length=100),
        ),
        migrations.AlterField(
            model_name='loan',
            name='transaction_no',
            field=models.CharField(blank=True, help_text='Enter the Transaction Number', max_length=30),
        ),
    ]
