# Generated by Django 4.2.7 on 2024-09-26 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mashinani', '0007_alter_application_allocation_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanee',
            name='national_id_no',
            field=models.CharField(help_text='Enter National Identification Number:', max_length=100),
        ),
    ]
