# Generated by Django 4.2.7 on 2024-09-27 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mashinani', '0008_alter_loanee_national_id_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('full_name', models.CharField(help_text='Enter Full Name', max_length=50)),
                ('email_address', models.EmailField(help_text='Enter Email Address', max_length=50)),
                ('subject', models.CharField(blank=True, help_text='Enter Subject', max_length=100)),
                ('message', models.CharField(blank=True, help_text='Enter Message', max_length=500)),
            ],
        ),
    ]
