# Generated by Django 4.2.7 on 2024-09-27 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mashinani', '0009_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(blank=True, help_text='Enter Message'),
        ),
    ]
